# Generated by Django 4.1.4 on 2022-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('grade_type', models.IntegerField(blank=True, null=True)),
                ('student_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('class_number', models.IntegerField()),
                ('student_id', models.CharField(default='<dj<dj<django.db.models.fields.IntegerField>', max_length=8)),
            ],
        ),
    ]
